name: News Digest Bot

on:
  schedule:
    - cron: '17 2,6,10,14,18 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Обновил до v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run summary script
        env:
          FRESHRSS_URL: ${{ secrets.FRESHRSS_URL }}
          FRESHRSS_USER: ${{ secrets.FRESHRSS_USER }}
          FRESHRSS_PASS: ${{ secrets.FRESHRSS_PASS }}
          OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CATEGORIES_AI: ${{ secrets.CATEGORIES_AI }}
          CATEGORIES_DIRECT: ${{ secrets.CATEGORIES_DIRECT }}
        run: python summary.py
